gText_Birch_Welcome::
    .string "Hello there! Good to meet you!\n"
    .string "You can call me Spruce!\p"
    .string "I used to be a Pokémon trainer, just\n"
    .string "like your parents.\p"
    .string "Nowadays, people just call me\n"
    .string "“Professor” though.\p"
    .string "$"

gText_Birch_Pokemon::
	.string "TAKE A LOOK AT MY BOMB-ASS TYRANITAR!\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
    .string "This land is crawling with \n"
    .string "Pokémon in every nook and cranny!\p"
    .string "As humans, we co-exist with Pokémon\n"
    .string "and with nature.\p"
    .string "I've made it my mission to learn \n"
    .string "everything I can about Pokémon\l"
    .string "and the world we live in!\p"
    .string "Oh, I'm not being very neighbourly!\n"
    .string "Please, tell me about yourself!\p"
	.string "$"

gText_Birch_AndYouAre::
    .string "Which of these photos is you?$"

gText_Birch_BoyOrGirl::
    .string "This on the left?\n"
    .string "Or the right?$"

gText_Birch_WhatsYourName::
    .string "Ayuh, I see it now.\n"
    .string "And, remind me how you spell your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
    .string "Right, thanks for the reminder!\n"
    .string "{PLAYER}{KUN}, I'm so excited you \l"
    .string "will be joining us in Fogvale town.\p"
    .string "$"

gText_Birch_AreYouReady::
    .string "I don't want to spoil the suprise,\n"
    .string "but I think you'll be happy here.\p"
    .string "The region of Oparlis is teeming\n"
    .string "with Pokemon, friends, and nature.\l"
    .string "But you'll see that soon enough.\n"
    .string "Your very own adventure, as \n"
    .string "they say, is about to unfold.\p"
    .string "$"
